"""
skills.txt 批量管理（pip requirements.txt 风格）

格式：
- 每行一个 source（自动嗅探 type，复用 sources.detect_source_type）
- # 开头为注释，空行忽略
- 行尾 # 之后的部分为行内注释（仅在前面有空格分隔时识别）

示例 skills.txt：
  # 团队公共 skill
  https://github.com/foo/bar.git
  @your-scope/skill-name     # private-npm 包
  ./local-skill              # 本地路径

借鉴自 agent-skills-hub 的 `skill list > skills.txt` + `skill install skills.txt`，
但本项目不依赖 GitHub repo 概念，source 自动按 detect_source_type 嗅探。
"""

from pathlib import Path
from typing import Dict, List, Optional, Union

from . import linker, manifest, sources, store


# ---------------------------------------------------------------------------
# 解析 / 导出
# ---------------------------------------------------------------------------

def parse_requirements_file(path: Union[Path, str]) -> List[Dict]:
    """
    解析 skills.txt。

    Returns:
        [{source: str, line_no: int, comment: Optional[str]}]
        只返回有效 source 行（已剥离注释、空行）。
    """
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"skills.txt 不存在: {p}")

    results: List[Dict] = []
    with open(p, "r", encoding="utf-8") as f:
        for idx, raw in enumerate(f, start=1):
            line = raw.rstrip("\n").rstrip("\r")
            stripped = line.strip()
            if not stripped:
                continue
            if stripped.startswith("#"):
                continue
            # 行内注释：要求 # 前必须有空白字符（兼容包名里的 # 极少情况）
            comment: Optional[str] = None
            source = stripped
            for marker in (" #", "\t#"):
                if marker in source:
                    head, _, tail = source.partition(marker)
                    source = head.strip()
                    comment = tail.strip()
                    break
            if not source:
                continue
            results.append({
                "source": source,
                "line_no": idx,
                "comment": comment,
            })
    return results

def export_skills_txt(out_path: Optional[Union[Path, str]] = None,
                      include_comments: bool = True) -> str:
    """
    从 manifest 导出 skills.txt。

    Args:
        out_path: 输出文件路径；None 则只返回字符串
        include_comments: 是否在每行 source 后追加 `# name@version (type)` 注释

    Returns:
        生成的文本内容（始终返回，便于上层直接打印）
    """
    skills = manifest.list_skills()
    lines: List[str] = []
    if include_comments:
        lines.append("# skills.txt - generated by skill-store-manager")
        lines.append("# 每行一个 source，# 开头为注释，空行忽略")
        lines.append("")

    for name in sorted(skills.keys()):
        entry = skills[name]
        src = entry.get("source") or {}
        ref = src.get("ref")
        stype = src.get("type", "?")
        version = entry.get("version", "?")
        if not ref:
            # adopted 或缺失 source.ref 的条目无法重装
            if include_comments:
                lines.append(f"# {name}@{version} ({stype}) - 无 source.ref，跳过导出")
            continue
        if include_comments:
            lines.append(f"{ref}  # {name}@{version} ({stype})")
        else:
            lines.append(ref)

    content = "\n".join(lines) + "\n" if lines else ""
    if out_path is not None:
        out = Path(out_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(content, encoding="utf-8")
    return content


# ---------------------------------------------------------------------------
# 批量安装 / 同步
# ---------------------------------------------------------------------------

def install_from_file(file_path: Union[Path, str],
                       *,
                       force: bool = False,
                       auto_link: bool = False,
                       link_scope: str = "global",
                       link_cwd: Optional[Path] = None,
                       link_type: str = linker.LINK_TYPE_AUTO,
                       dry_run: bool = False) -> Dict:
    """
    从 skills.txt 批量安装。

    Args:
        file_path:  skills.txt 路径
        force:      已存在的同名 skill 是否覆盖（store.add_skill_from_path overwrite）
        auto_link:  安装后是否立即按 link_scope 链接到工具
        link_scope: 'global' | 'project'，仅 auto_link=True 时生效
        link_cwd:   project scope 的项目根
        link_type:  'auto' | 'symlink' | 'copy'
        dry_run:    只解析不实际安装

    Returns:
        {success: [...], failed: [...], skipped: [...]}
        每条形如 {source, name?, version?, type?, error?}
    """
    items = parse_requirements_file(file_path)
    success: List[Dict] = []
    failed: List[Dict] = []
    skipped: List[Dict] = []

    for item in items:
        src = item["source"]
        if dry_run:
            stype = sources.detect_source_type(src)
            if stype == "unknown":
                failed.append({
                    "source": src,
                    "error": "无法识别来源类型（local/git/private-npm/url 都不匹配）",
                    "line_no": item["line_no"],
                })
                continue
            success.append({
                "source": src, "type": stype, "action": "would-install",
                "line_no": item["line_no"],
            })
            continue

        # 1. 下载到临时目录
        try:
            skill_dir, version, stype, ref = sources.install(src)
        except Exception as e:
            failed.append({
                "source": src, "error": f"install 失败: {e}",
                "line_no": item["line_no"],
            })
            continue

        name = skill_dir.name

        # 2. 加入中央仓库
        try:
            target = store.add_skill_from_path(skill_dir, name=name,
                                                overwrite=force)
        except FileExistsError:
            skipped.append({
                "source": src, "name": name, "version": version,
                "type": stype, "error": "already exists（用 --force 覆盖）",
                "line_no": item["line_no"],
            })
            continue
        except Exception as e:
            failed.append({
                "source": src, "name": name, "error": f"store 失败: {e}",
                "line_no": item["line_no"],
            })
            continue

        # 3. 写 manifest
        try:
            manifest.add_skill_entry(name, version, stype, ref)
        except Exception as e:
            failed.append({
                "source": src, "name": name,
                "error": f"manifest 写入失败: {e}",
                "line_no": item["line_no"],
            })
            continue

        record = {
            "source": src, "name": name, "version": version,
            "type": stype, "store_path": str(target),
            "line_no": item["line_no"],
        }

        # 4. 可选：自动 link
        if auto_link:
            link_results = linker.link_to_all(
                target, scope=link_scope, cwd=link_cwd, link_type=link_type,
            )
            for tk, r in link_results.items():
                if r.get("ok"):
                    manifest.add_linked_target(
                        name, tool_key=tk,
                        scope=link_scope,
                        link_type=r.get("link_type", linker.LINK_TYPE_SYMLINK),
                        project_root=str(Path(link_cwd).resolve())
                            if link_scope == "project" and link_cwd else None,
                    )
            record["linked"] = link_results

        success.append(record)

    return {"success": success, "failed": failed, "skipped": skipped}

def sync_from_file(file_path: Union[Path, str],
                    *,
                    scope: str = "global",
                    cwd: Optional[Path] = None,
                    targets: Optional[List[str]] = None,
                    link_type: str = linker.LINK_TYPE_AUTO,
                    dry_run: bool = False) -> Dict:
    """
    从 skills.txt 批量把 skill 同步（link）到工具目录。

    与 install_from_file 的区别：本函数假定 skills 已经在中央仓库中，
    只做 link 不做下载。如果某行的 skill 不在 store 中，会记入 failed。

    匹配逻辑：
    - 如果 source 是本地路径或包名，取 basename 作为 skill name
    - 否则按 sources.install 的命名约定（skill_dir.name）

    Returns:
        {success: [{name, results}], failed: [{source, error}]}
    """
    items = parse_requirements_file(file_path)
    success: List[Dict] = []
    failed: List[Dict] = []

    for item in items:
        src = item["source"]
        # 优先按 manifest.source.ref 反查（最可靠）；查不到再退化到 _guess_skill_name
        name = _resolve_name_from_source(src)
        if name is None or not store.has_skill(name):
            failed.append({
                "source": src, "name": name,
                "error": (f"skill {name!r} 不在中央仓库中，请先 install"
                          if name else f"无法解析 skill 名（manifest 中无匹配 source.ref）"),
                "line_no": item["line_no"],
            })
            continue

        skill_path = store.get_skill_path(name)
        results = linker.link_to_all(
            skill_path, targets=targets, scope=scope, cwd=cwd,
            link_type=link_type, dry_run=dry_run,
        )
        if not dry_run:
            for tk, r in results.items():
                if r.get("ok") and r.get("action") in ("created", "kept"):
                    manifest.add_linked_target(
                        name, tool_key=tk, scope=scope,
                        link_type=r.get("link_type", linker.LINK_TYPE_SYMLINK),
                        project_root=str(Path(cwd).resolve())
                            if scope == "project" and cwd else None,
                    )
        success.append({
            "source": src, "name": name, "results": results,
            "line_no": item["line_no"],
        })

    return {"success": success, "failed": failed}


def _resolve_name_from_source(source: str) -> Optional[str]:
    """
    解析 source 字符串对应的 skill name，优先级：
      1. manifest 中已记录的 source.ref 精确匹配
      2. _guess_skill_name 的猜测结果（且 store 中存在该 name）
    都没命中返回 None。
    """
    src = source.strip()
    skills = manifest.list_skills()
    # 1. 精确匹配 source.ref
    for name, entry in skills.items():
        ref = (entry.get("source") or {}).get("ref")
        if ref and ref == src:
            return name
    # 2. 猜测
    guessed = _guess_skill_name(src)
    if guessed and store.has_skill(guessed):
        return guessed
    return None

def _guess_skill_name(source: str) -> str:
    """
    从 source 字符串猜测 skill 目录名。

    注意：此函数仅用作 fallback（精确匹配失败时），因为 sources.install
    返回的 skill_dir.name 实际取决于源压缩包/npm 包的内部目录结构，
    无法只从 source 字符串 100% 推断。

    - 本地路径：取 basename（与 sources._find_skill_root 找到的子目录名一致的概率高）
    - git URL：取最后一段去 .git
    - npm 包名：取 / 后的部分（与 _read_pkg_name 的去 scope 逻辑一致）
    - URL：取 path 最后一段去常见后缀
    """
    s = source.strip().rstrip("/")
    # 去 query/fragment
    for sep in ("?", "#"):
        if sep in s:
            s = s.split(sep, 1)[0]
    # 去常见压缩后缀
    for suffix in (".tar.gz", ".tgz", ".tar", ".zip", ".git"):
        if s.lower().endswith(suffix):
            s = s[: -len(suffix)]
            break
    # 取 path 最后一段
    if "/" in s:
        s = s.rsplit("/", 1)[1]
    return s
